# Deployment aplicação web conversão peso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-conversao-peso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-conversao-peso
  template:
    metadata:
      labels:
        app: web-conversao-peso
    spec:
      containers:
        - name: web-conversao-peso
          image: norbertosantos/conversao-peso:v1
          ports:
            - containerPort: 5000

---
# Service para Deployment do conversao-peso
apiVersion: v1
kind: Service
metadata:
  name: web-conversao-peso-service
spec:
  selector:
    app: web-conversao-peso
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30002
  type: NodePort 